name: cicd-pipeline

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      env:
        PASSWORD: ${{ secrets.PASSWORD }}
      run: mvn compile jib:build --file pom.xml

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Authenticate with Google Cloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.SA_CICD }}'

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: crdemo-cicd
          region: us-central1
          image: anuragpatil05524/ccrdemo:cicd001
          allow-unauthenticated: true

      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}

